p1/ProTwo/ProTwo/ProTwo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from appTwo import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^users/',include('appTwo.urls')),
    url(r'^admin/', admin.site.urls),
]

p1/ProTwo/ProTwo/appTwo/urls.py
from django.conf.urls import url
from appTwo import views

urlpatterns = [
    url(r'^$',views.users,name='users'),
]

p1/a1/urls.py
from django.conf.urls import url
from a1 import views
from django.urls import path,re_path



app_name =  'a1'

urlpatterns= [
    re_path(r'^register/$',views.register,name='register'),
    #re_path(r'^other/$',views.other,name='other'),
    re_path(r'^user_login/$',views.user_login,name='user_login'),

]

p1/p1/urls.py
from django.contrib import admin
from django.urls import path,re_path
from a1 import views
from django.conf.urls import include

urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    re_path(r'^a1/',include('a1.urls')),
    re_path(r'^logout/$',views.user_logout,name='logout'),
    re_path(r'special/',views.special,name='special')
]

p1/ProTwo/ProTwo/appTwo/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254,unique=True)

p1/a1/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.DO_NOTHING,)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

p1/ProTwo/ProTwo/appTwo/forms.py
from django import forms
from appTwo.models import User

class NewUserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = '__all__'

p1/a1/forms.py
from django import forms
from django.contrib.auth.models import User
from  a1.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

p1/ProTwo/ProTwo/appTwo/views.py
from django.shortcuts import render
# from django.http import HttpResponse
# from appTwo.models import User
from appTwo.forms import NewUserForm
# Create your views here.

def index(request):
    return render(request,'appTwo/index.html')

def users(request):

    form = NewUserForm()

    if request.method == "POST":
        form = NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')

    return render(request,'appTwo/users.html',{'form':form})

p1/a1/views.py
from django.shortcuts import render
from django.http import HttpResponse
from a1.forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
# Create your views here.


def index(request):
    return render(request,'a1/index.html')

@login_required
def special(request):
    return HttpResponse("You logged in, YAY!!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False


    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            print("NAME is:"+user.username)
            print("PWD is:"+user.password)

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm

    return render(request,'a1/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('Username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)
        #user = authenticate(username='ask3',password='djangobla!')
        #print("USER IS:"+user)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Your account is not active.")

        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid Login Details Supplied")

    else:
        return render(request,'a1/login.html',{})

p1/ProTwo/ProTwo/templates/appTwo/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome!</h1>
        <h2>Go to /users to sign up!</h2>
      </div>
    </div>


  </body>
</html>

p1/ProTwo/ProTwo/templates/appTwo/users.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Users</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">
      <h1>Please sign up here!</h1>
      <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class='btn btn-primary' value="Submit">
      </form>
    </div>



  </body>
</html>

p1/templates/a1/base.html
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- CSS only -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous"> -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
  <nav class='navbar navbar-default navbar-static-top'>
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
      <div class="container">

          <ul class="nav navbar-nav">
            <li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'a1:register' %}">Register</a></li>

            {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'a1:user_login' %}">Login</a></li>
            {% endif %}



          </ul>

      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
    <!-- Latest compiled and minified JavaScript -->
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    -->
    <!-- JavaScript Bundle with Popper
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    -->
  </body>
</html>

p1/templates/a1/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">">
  </head>
  <body>
    <h1>Fill out the form</h1>
    <div class="container">
      <form method="POST">
          {{form.as_p}}
          {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>


    </div>

  </body>
</html>

p1/templates/a1/index.html
{% extends "a1/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django level 5</h1>

</div>
{% endblock %}

p1/templates/a1/login.html
{% extends 'a1/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'a1:user_login' %}" method="post" onsubmit="showName(Username.value,password.value)">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="Username" placeholder="Enter your Username here">

    <label for="password">Password</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>

</div>
<script type="text/javascript">
  function showName(un,pw) {
  alert("The form was about to be submitted "+un+"."+pw);
}
</script>

{% endblock %}

p1/templates/a1/other.html
<!DOCTYPE html>
{% extends "a1/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of template inheritance!</h2>
    {% endblock %}

p1/templates/a1/registration.html
{% extends 'a1/base.html' %}


{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering</h1>
  {% else %}
  <h1>Register here</h1>
  <h3>Fill out the form:</h3>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">
  </form>

  {% endif %}

</div>


{% endblock %}

p1/templates/a1/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'a1:other' %}">The Other Page</a>
    <a href="{% url 'admin:index' %}">Admin</a>
    <a href="{% url 'index' %}">INdex</a>

  </body>
</html>